fix: failed token transfer 500 error
ArdentHQ/arkscan pull request #1046
Opened 2024-12-09 19:22 UTC by alexbarnsley

## Summary

https://app.clickup.com/t/86dvcj0yr

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2024-12-10 15:39 UTC, alfonsobries commented
@alexbarnsley conflicts

2024-12-11 10:40 UTC, ItsANameToo approved these changes

2024-12-11 10:41 UTC, ItsANameToo requested changes

2024-12-11 10:41 UTC, ItsANameToo commented on database/factories/TransactionFactory.php
> +                'recipient_address' => Network::knownContract('consensus'),
is this correct? 🤔

2024-12-11 12:31 UTC, ItsANameToo approved these changes

2024-12-11 12:32 UTC, merged