[WIP] feat: reintegrate username functionality
ArdentHQ/arkscan pull request #1101
Opened 2024-12-18 18:34 UTC by alexbarnsley

## Summary

https://app.clickup.com/t/86dvdmpme

Mostly reverting username removals from #1000

TODO:

- [ ] Add tests
- [ ] PHPStan
- [ ] Review the below files for username first, known first, or enforce one of the two

- resources/scripts/vote-report.sh - add username?
- resources/views/app/wallet.blade.php - prioritize username or known name?
- resources/views/components/general/identity-iconless.blade.php - prioritize username or known name?
- resources/views/components/stats/insights/desktop/validator-row.blade.php - prioritize username or known name?
- resources/views/components/stats/insights/mobile/validator-row.blade.php - prioritize username or known name?

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2025-01-17 11:20 UTC, ItsANameToo requested changes

2025-01-17 11:20 UTC, ItsANameToo commented on resources/views/components/wallet/overview/wallet.blade.php
> +        :value="$wallet->usernameBeforeKnown()"
you'll want the "known name" to always overrule on-chain ones as we only set this for specific reasons (e.g. to highlight legit accounts, or to highlight someone who abuses the usernames)

2025-01-17 11:20 UTC, ItsANameToo commented on tests/Unit/Console/Commands/CacheKnownWalletsTest.php
> +it('should cache the known wallet name if doesnt have validator name', function () {
known wallet > username

2025-01-17 15:39 UTC, alfonsobries commented on app/Models/Concerns/Transaction/CanBeSorted.php
> +    }
@alexbarnsley 

I think we need to add some tests specifically for this scope. It must be getting called somewhere because we don't have issues with test coverage, but since the query is quite complex, I think it would be good to have some dedicated tests.

2025-01-22 02:22 UTC, alexbarnsley commented on app/Models/Concerns/Transaction/CanBeSorted.php
> +    }
I've refactored that method so it works correctly now. I've also [added a card](https://app.clickup.com/t/86dvt4djg) to adjust it further to consider known wallets when sorting.

I wrote a more comprehensive set of tests for ascending and descending to have a scenario for each possible use-case:

- Name + Address ASC
- Name + Address ASC
- empty value always last

2025-01-22 10:42 UTC, samharperpittam approved these changes

2025-01-22 14:58 UTC, alfonsobries approved these changes

2025-01-22 16:23 UTC, merged