refactor: updated pagination
ArdentHQ/arkscan pull request #225
Opened 2023-05-18 23:00 UTC by alexbarnsley

## Summary

https://app.clickup.com/t/861mr8qqq

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-05-22 20:45 UTC, alexbarnsley commented
@ItsANameToo I've kept the pagination internal to this project. Do you want it moved to foundation?

2023-05-23 08:31 UTC, samharperpittam requested changes
- Pretty translation when viewing pagination on mobile on Top Accounts page
<img width="346" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/374967ac-d1ba-4e5c-ac91-11576436d97f">

---

- When viewing the Top Accounts page in mobile, the dropdown looks disabled (not sure if that's covered within this PR or not, if not i can create a new task)
<img width="240" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/8ebf1ef5-519b-4018-8ce8-4fea03ea0139">

---

- The "Enter Page Number" box isn't styled correctly. Again unsure if that's covered within this PR or not. 

Design
<img width="428" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/90f8ea00-8dd2-4e66-9c4a-e9de14ff2fcf">

Imp
<img width="359" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/78e98fdb-796d-46e2-a58b-f395cedad424">

---

- The pagination icons look like they're thicker in the designs? 
Des
<img width="105" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/72080430-f43c-481e-9c0d-c8aa36985570">

Imp
<img width="79" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/172b486d-b276-4e77-9556-3594c02c2cc6">

2023-05-23 12:14 UTC, samharperpittam requested changes
Sorry @alexbarnsley  - Just noticed 2 other minor things.

1.  The styling of the page number search is incorrect in dark mode

Des
<img width="457" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/31ffa7eb-d350-48fb-aa76-f9db2305e397">


Imp
<img width="593" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/555a496e-1558-4d78-bf41-865ee82cf62c">

---

2. When viewing the pagination in mobile, the page numbers are missing the `Page` text. 

Design
<img width="455" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/4ad7351c-4c2b-4d4e-93e1-4c6e5591acf1">

Imp
<img width="352" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/3832940c-7095-4950-8ba6-dba5fad4b721">

---

Sorry I didn't report them before.

2023-05-23 13:27 UTC, samharperpittam approved these changes

2023-05-24 07:58 UTC, ItsANameToo approved these changes

2023-05-24 07:59 UTC, merged