[wip] feat: initial exchanges page
ArdentHQ/arkscan pull request #227
Opened 2023-05-19 00:52 UTC by alexbarnsley

## Summary

https://app.clickup.com/t/861mruakp

TODO:

- [ ] Tests
- [ ] Mobile Layout (currently uses standard mobile table formatting)
- [ ] Placeholder Logo
- [ ] Dropdowns

Requires https://github.com/ArkEcosystem/laravel-foundation/pull/562 & https://github.com/ArkEcosystem/laravel-foundation/pull/563

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-05-23 00:05 UTC, alfonsobries approved these changes
im approving since my only comment is more like a suggestion

2023-05-23 00:05 UTC, alfonsobries commented on routes/web.php
> +})->name('exchanges');
I think we should move this to a controller

2023-05-23 00:08 UTC, alfonsobries commented
corners are cut off 
<img width="612" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/17262776/f58d8ab4-b200-4ac0-b410-919abeefbf8d">

2023-05-23 00:09 UTC, alfonsobries commented
border on icons is missing 

Design:
![image](https://github.com/ArdentHQ/arkscan/assets/17262776/eeb6b7e3-31e8-4aaa-832c-bba181198974)

Implementation
<img width="482" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/17262776/96152d12-ce00-48b5-8bf6-680006923063">

2023-05-23 00:10 UTC, alfonsobries commented
On sm creen the submit wallet button is below

Design:
![image](https://github.com/ArdentHQ/arkscan/assets/17262776/5fb70cb5-9b3d-4b4a-8ef6-2f65a2f4201c)


Implementation
<img width="744" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/17262776/7ab54e0b-5a4d-4441-9b19-7b18cabc782b">

2023-05-23 00:11 UTC, alfonsobries commented
also card header color is not correct, is blueish in design

Design

![image](https://github.com/ArdentHQ/arkscan/assets/17262776/334fb6b7-6988-4d49-9c20-d21cad461f5e)


Implementation
<img width="605" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/17262776/3dd20e27-c6b2-403c-84c2-d7d2be619ba5">

2023-05-23 00:12 UTC, alfonsobries commented
Md screen does not show the volume

Design
![image](https://github.com/ArdentHQ/arkscan/assets/17262776/9a4cdcdc-7129-4ee2-9db7-83dd4c359e3a)


Implementation
<img width="722" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/17262776/1ee83aa1-fc13-4fa7-bd58-a7188b1c9d3b">

2023-05-23 00:13 UTC, alfonsobries commented
Button says "submit wallet" but should say "submit exchange"

<img width="213" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/17262776/1ca90e0f-4431-47de-9f21-eefab5450edd">

2023-05-23 00:14 UTC, alfonsobries commented
lg screen (1024) is broken

Design:

![image](https://github.com/ArdentHQ/arkscan/assets/17262776/39cba535-964a-4c8c-b011-afc6eaa13022)


Implementation

<img width="760" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/17262776/7ea89961-0f7a-4627-937a-bcd0304ff188">

2023-05-23 00:17 UTC, alfonsobries commented
margin above blue box should be 32px and is 24px 
<img width="334" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/17262776/db931d2f-1f81-4590-98ea-c5e520c70f21">

2023-05-23 00:18 UTC, alfonsobries requested changes
design needs adjustments

2023-05-23 21:12 UTC, alexbarnsley commented
@alfonsobries Fixed all the points apart from:

- lg screen (1024) is broken - **this is because there's no `md-lg` breakpoint yet - added here https://github.com/ArkEcosystem/laravel-foundation/pull/568**
- Md screen does not show the volume - **Same as above**
- Button says "submit wallet" but should say "submit exchange" - **Not implemented yet - https://app.clickup.com/t/861mrubj4**
- also card header color is not correct, is blueish in design - **that's a mistake in the designs, I confirmed with Oleg that it should be `gray-100`**

I'll re-open the PR once the foundation change is merged

2023-05-24 10:39 UTC, samharperpittam requested changes
The table styling at 640 is incorrect.

Design
<img width="695" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/7d23878d-025e-43ef-869d-f603fd75e547">


Imp
<img width="718" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/5985e09a-fea8-4750-b3bf-72159059aecd">

2023-05-24 10:50 UTC, samharperpittam requested changes
The dropdown boxes are 4px too big in height. Should be 44px.

<img width="332" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/8d8c50d3-6fbd-4506-8910-f705d3a7e3b2">

2023-05-24 14:35 UTC, ItsANameToo approved these changes

2023-05-24 14:35 UTC, merged