feat: use usd in exchanges table
ArdentHQ/arkscan pull request #239
Opened 2023-05-25 16:39 UTC by alfonsobries

## Summary

Closes https://app.clickup.com/t/861mruapk

Since we can only retrieve USD from coingecko, im defaulting the currency to USD, see comments of pr for fetching details --> https://github.com/ArdentHQ/arkscan/pull/237

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-05-25 20:23 UTC, alexbarnsley requested changes
quickie

2023-05-25 20:23 UTC, alexbarnsley commented on resources/views/components/tables/desktop/exchanges.blade.php
> +                <span>(USD)</span>
Can this use the lang for now?

```suggestion
                <span>(@lang('currencies.usd.currency'))</span>
```

2023-05-25 20:23 UTC, alexbarnsley commented on resources/views/components/tables/desktop/exchanges.blade.php
> +                <span>(USD)</span>
Can this use the lang for now?

```suggestion
                <span>(@lang('currencies.usd.currency'))</span>
```

2023-05-25 22:31 UTC, alexbarnsley commented on resources/views/components/tables/desktop/exchanges.blade.php
> +                <span>(@lang('currencies.usd.currency'))</span>
My bad, it's a config file :hide:

```suggestion
                <span>({{ config('currencies.usd.currency') }})</span>
```

2023-05-25 22:31 UTC, alexbarnsley commented on resources/views/components/tables/desktop/exchanges.blade.php
> +                <span>(@lang('currencies.usd.currency'))</span>
```suggestion
                <span>({{ config('currencies.usd.currency') }})</span>
```

2023-05-25 22:32 UTC, alexbarnsley approved these changes

2023-05-26 09:06 UTC, samharperpittam commented
@alfonsobries - PR looks good but just a quick question, were you able to fetch more prices for exchanges than I have here? Just checking my local is setup correctly.

<img width="983" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/1c83ed20-69fc-4ed5-a6d5-4abc542809a9">

2023-05-26 15:25 UTC, alfonsobries commented
@samharperpittam For me it loads 7 prices but fixed an issue that was causing the job to fail after some time, you can try again,

Consider that it may take 2 minutes to load all of them because it only tries to load data for 10 exchanges per minute, so, if you keep the queue running, it will run the second batch after 1 minute

2023-05-30 09:51 UTC, alexbarnsley commented
>Consider that it may take 2 minutes to load all of them because it only tries to load data for 10 exchanges per minute, so, if you keep the queue running, it will run the second batch after 1 minute

@alfonsobries which command are you running as the `exchanges:load` command doesn't run any jobs :thinking:

2023-05-30 12:07 UTC, merged