refactor: public key modal updates
ArdentHQ/arkscan pull request #284
Opened 2023-06-06 22:20 UTC by alexbarnsley

## Summary

https://app.clickup.com/t/861mwh6gn

requires https://github.com/ArkEcosystem/laravel-foundation/pull/571

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-06-09 14:58 UTC, samharperpittam requested changes
Should be able to close the modal by pressing escape.

2023-06-09 15:00 UTC, samharperpittam requested changes
`X` should be white on hover

Des
<img width="221" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/dbe6fd88-3dd2-43d4-a0ca-2032ef6a7f57">

Imp
<img width="111" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/40b95c73-b193-47b0-a952-0abbd038ebdb">

2023-06-13 11:11 UTC, samharperpittam requested changes
<img width="216" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/ea57502e-6e79-4255-a4f4-1ec310bb6088">

Same issue with the copy button here @alexbarnsley

---

This modal also has some responsive issues

960 - very wide
<img width="846" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/e0b943a4-87b2-44be-9a56-47fd1f5f9b72">
 
 768 - off screen
<img width="599" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/264bbd75-8337-43f9-9d8e-9c72d238cbaa">

640
<img width="556" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/20efe96c-d5d4-40b2-966d-6520a54821a0">

375
<img width="329" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/18280ce2-4a56-4898-b254-4bfeaf10e90b">

Might just need to truncate the address like we do for the existing pubkey modal on scan.

2023-06-13 13:06 UTC, samharperpittam approved these changes

2023-06-13 13:42 UTC, ItsANameToo approved these changes

2023-06-13 13:42 UTC, merged