refactor: wallet transactions table header
ArdentHQ/arkscan pull request #303
Opened 2023-06-14 13:04 UTC by alexbarnsley

## Summary

https://app.clickup.com/t/861mwntgb

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-06-15 13:48 UTC, samharperpittam requested changes
@alexbarnsley  - The results value displays a max of 15 records. 

- Find a wallet with a lot of records (such as `
DArvWfH5nMDT38tWmo5k461vMQpRXHQWX9`)
- See "Showing 15 Results" even though there's 37 pages of records to view.
- Suspect it's just totalling up the records per page rather than total record amount

<img width="1368" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/d504967c-fc57-4f5c-b67d-ed101d9052b2">

2023-06-15 13:50 UTC, samharperpittam commented
Probably for a different task but this element is ugly when switching pages. Think we need to ammend the table skeleton to preserve the table outline. Will create a task for this. 

<img width="900" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/48764bb3-18dc-426c-a1a8-3da5c13a2db5">

2023-06-15 21:25 UTC, alexbarnsley commented
I've done desktop skeleton and added the base mobile skeleton but the latter needs adjusting. I've commented on the card you created to deal with that

2023-06-16 08:51 UTC, samharperpittam approved these changes

2023-06-16 09:20 UTC, ItsANameToo approved these changes

2023-06-16 09:20 UTC, merged