Feat/transaction export functionality
ArdentHQ/arkscan pull request #362
Opened 2023-06-29 23:01 UTC by alexbarnsley

## Summary

https://app.clickup.com/t/861mxjtqe

Requires https://github.com/ArdentHQ/arkscan/pull/360 to be merged first

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-06-30 14:15 UTC, samharperpittam requested changes
Slight issue
<img width="1479" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/44671015/1d6daaac-cccf-4164-898a-067d421190c7">

2023-07-04 09:54 UTC, ItsANameToo requested changes

2023-07-04 09:54 UTC, ItsANameToo commented on resources/js/export.js
> +        if (transaction.type === 6 && transaction.typeGroup === 1) {
```suggestion
        if (transaction.type === 6 && transaction.typeGroup === 1) {
```

might be nice to change this to enums. They exist in PSDK or in the JS crypto package iirc

2023-07-04 09:54 UTC, ItsANameToo commented on resources/js/export.js
> +                        totalAmount += recipientData.amount / 1e8;
change this to a method that takes arktoshi and changes it to a "regular" number, as it's reused quite a bit

2023-07-04 09:54 UTC, ItsANameToo commented on resources/views/components/modals/export-transactions/export-status.blade.php
> +        <div x-show="exportStatus === 'PENDING_DOWNLOAD'">
maybe an enum for this as well?

2023-07-04 12:59 UTC, ItsANameToo approved these changes

2023-07-04 13:14 UTC, merged