feat: export custom date range
ArdentHQ/arkscan pull request #389
Opened 2023-07-06 21:32 UTC by alexbarnsley

## Summary

https://app.clickup.com/t/862k258az

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-07-07 09:03 UTC, alexbarnsley commented
Yes I forgot :sadmici:

https://github.com/ArkEcosystem/laravel-foundation/pull/585

2023-07-07 10:03 UTC, ItsANameToo requested changes

2023-07-10 11:42 UTC, alexbarnsley commented on resources/views/components/input/date-picker.blade.php
> +    'minDate' => 0,
Yeh it was setting this in the range but it turns out it needs to be a date object and not just a timestamp

2023-07-11 08:30 UTC, ItsANameToo approved these changes

2023-07-11 08:37 UTC, samharperpittam approved these changes

2023-07-11 08:39 UTC, merged