Feat/ark deeplink
ArdentHQ/arkscan pull request #67
Opened 2022-08-11 22:43 UTC by alfonsobries

## Summary

Closes https://app.clickup.com/t/2qak9v1
Depends on releasing https://github.com/ArdentHQ/arkvault-url-php

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2022-08-15 14:38 UTC, alfonsobries commented
@ItsANameToo new dependency https://github.com/ArkEcosystem/laravel-foundation/pull/457

2022-08-15 15:09 UTC, alfonsobries commented
@ItsANameToo ✅

2022-08-17 09:05 UTC, ItsANameToo requested changes
- at 360px the delegate page pushes the vote button away. Can you make it take some additional space from the delegate name instead? 
<img width="417" alt="image" src="https://user-images.githubusercontent.com/35610748/185074720-7bbc6efd-b026-40bf-bc38-016e8281ea4a.png">

2022-08-24 15:51 UTC, alfonsobries commented on app/ViewModels/WalletViewModel.php
> +        return ArkVaultUrlBuilder::get()->generateVote($this->address());
@ItsANameToo :hide: fixed

2022-08-24 15:51 UTC, alfonsobries commented
@ItsANameToo ✅

2022-08-25 14:58 UTC, ItsANameToo approved these changes

2022-08-25 14:59 UTC, merged