[wip] feat: arkconnect navbar button
ArdentHQ/arkscan pull request #799
Opened 2024-03-19 23:20 UTC by alexbarnsley

## Summary

https://app.clickup.com/t/86drwqqf8

Todo:

- [ ] Mobile state - awaiting designs

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2024-03-20 18:07 UTC, alfonsobries requested changes
This doesnt seem right
![image](https://github.com/ArdentHQ/arkscan/assets/17262776/a93880a8-69d5-481a-a0a7-0c5d64ec196a)

![image](https://github.com/ArdentHQ/arkscan/assets/17262776/22a78451-afdb-4980-9979-da64bf0eb96c)

2024-03-20 18:08 UTC, alfonsobries requested changes
Other than the mode-color the design is not applied properly, design:

![image](https://github.com/ArdentHQ/arkscan/assets/17262776/854e6885-7da8-42c0-88e2-47629df238c0)

2024-03-20 18:09 UTC, alfonsobries reviewed
Finally the `hasExtension()` condition doesnt seem to work for me (i removed that condition to test this PR)

Tried to install the latest version of the arkconnect extension on chrome+mac and `window.arkconnect` is undefined, same happens if I run the develop version of the plugin, not sure if I missing something

2024-03-21 13:58 UTC, ItsANameToo requested changes
also extension doesn't get found locally, even though `window.arkconnect` is available in devtools

2024-03-21 13:58 UTC, ItsANameToo commented on webpack.mix.js
> -    )
? now it's no longer minimized 🤔

2024-03-22 00:14 UTC, alfonsobries requested changes
design is good now, but now the button is always disabled

![image](https://github.com/ArdentHQ/arkscan/assets/17262776/e51aeb65-bae1-4135-a06f-d1f6cf3b38a7)


Probably because of this line is never setting isLoading to false

https://github.com/ArdentHQ/arkscan/pull/799/files#diff-107b51fb3ed89d5d781341dc4e51b926a020477c468cf86edc0b9d24603e17d7R25-R27

Also in my case I have arkconnect, maybe when that function runs the window.arkconnect  is not set yet

2024-03-25 18:22 UTC, alfonsobries commented
working now @alexbarnsley

2024-03-26 08:57 UTC, ItsANameToo approved these changes

2024-03-26 08:57 UTC, merged