refactor: arkconnect dropdown my address
ArdentHQ/arkscan pull request #901
Opened 2024-05-14 14:08 UTC by alexbarnsley

## Summary

https://app.clickup.com/t/86dtgpxng

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2024-05-15 11:40 UTC, samharperpittam requested changes
The disabled state doesn't look correct. The text should be gray-500. Currently it appears as if it's selected rather than disabled.

Design
![image](https://github.com/ArdentHQ/arkscan/assets/44671015/59f8b1df-5a0c-4c0f-ac8c-a84c60aaeb95)


Implementation
![image](https://github.com/ArdentHQ/arkscan/assets/44671015/cb5d1ec0-8156-42aa-bdb0-edb8f8039125)

2024-05-16 10:48 UTC, alexbarnsley commented
@samharperpittam this should be fixed, would you mind taking another look please

2024-05-16 11:05 UTC, samharperpittam approved these changes

2024-05-16 13:36 UTC, ItsANameToo approved these changes

2024-05-16 13:41 UTC, merged